Rename FILE *logf and static void log(char *fmt, ...)
because gcc complains about them:

vdkfmt.c:133:7: warning: built-in function 'logf' declared as non-function
tapedd.c:246:7: warning: built-in function 'logf' declared as non-function
enaddr.c:174:13: warning: conflicting types for built-in function 'log'

even though it probably should not. <math.h> has not been included as
far as I can see.